import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import SessionContext from "@/components/SessionContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <SessionContext>
          <div className="page-wrapper">{children}</div>
        </SessionContext>
        <Footer />
      </body>
    </html>
  );
}
