import TopContent from "@/components/TopContent";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <TopContent />
      {children}
    </>
  );
}
