import ActiveLink from "@/components/ActiveLink";
import styles from "./layout.module.css";
import DashboardNav from "@/components/dashboard/DashboardNav";
import SignOutBtn from "@/components/account/SignOutBtn";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <section className={styles.mobileBtnContainer}>
        <DashboardNav />
      </section>
      <section className={styles.container}>
        <div className={styles.sideNav}>
          <ul>
            <li>
              <ActiveLink href="/konto" activeClassName={styles.active}>
                Edytuj Profil
              </ActiveLink>
            </li>
            <li>
              <ActiveLink href="/zakupy" activeClassName={styles.active}>
                Moje Zakupy
              </ActiveLink>
            </li>
            <li>
              <ActiveLink href="/filmy" activeClassName={styles.active}>
                Filmy
              </ActiveLink>
            </li>
            <li>
              <SignOutBtn />
            </li>
          </ul>
        </div>
        {children}
      </section>
    </>
  );
}
